#!/usr/bin/env python3
"""Regenerate CATALOG.md and site/index.html from the catalog entries.

    python3 scripts/build_catalog.py            # rewrite CATALOG.md and site/index.html
    python3 scripts/build_catalog.py --check    # exit 1 if either is stale (CI)

Both outputs are generated, so they can never silently disagree with the entries
on disk. Run scripts/validate_catalog.py first (this script does it for you and
aborts on errors).
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

from _catalog import CATEGORIES, KIND_LABEL, ROOT, TIER_BADGE, TIER_ORDER, iter_entries

CATALOG_MD = ROOT / "CATALOG.md"
SITE = ROOT / "site" / "index.html"
REPO_URL = "https://github.com/yangzhou-chaofan/awesome-gpt6-astra-game-prompts"

SECTION_RE = re.compile(r"^## (.+?)\s*$\n+(.*?)(?=\n## |\Z)", re.MULTILINE | re.DOTALL)


def read_sections(path: Path) -> dict[str, str]:
    body = path.read_text(encoding="utf-8")
    body = body.split("---", 2)[-1]  # drop frontmatter
    out: dict[str, str] = {}
    for name, text in SECTION_RE.findall(body):
        out[name.strip()] = " ".join(text.split())
    return out


def load() -> list[dict]:
    entries = []
    for path, meta in iter_entries():
        if "__error__" in meta:
            continue
        sections = read_sections(path)
        rel = path.relative_to(ROOT).as_posix()
        entries.append(
            {
                "id": meta["id"],
                "title": meta["title"],
                "category": meta["category"],
                "kind": meta["kind"],
                "tier": meta["tier"],
                "source_platform": meta["source_platform"],
                "source_url": meta["source_url"],
                "author": meta["author"],
                "has_prompt": bool(meta["has_prompt"]),
                "prompt_note": meta.get("prompt_note", ""),
                "stars": meta.get("stars"),
                "signals": meta.get("signals", []),
                "tags": meta.get("tags", []),
                "added": meta["added"],
                "what": sections.get("What it is", ""),
                "why": sections.get("Why it's recommended", ""),
                "path": rel,
            }
        )
    entries.sort(key=lambda e: (list(CATEGORIES).index(e["category"]), e["id"]))
    return entries


def render_markdown(entries: list[dict]) -> str:
    total = len(entries)
    tiers = {t: sum(1 for e in entries if e["tier"] == t) for t in TIER_ORDER}
    with_prompt = sum(1 for e in entries if e["has_prompt"])

    lines = [
        "# Catalog",
        "",
        f"> **{total}** GPT-6 Astra entries \u00b7 {len(CATEGORIES)} categories \u00b7 "
        f"{tiers['featured']} featured, {tiers['notable']} notable, {tiers['community']} community "
        f"\u00b7 {with_prompt} ship a prompt.",
        "",
        "The discovery layer: prompts, demos, tools and guides from across the GPT-6 Astra "
        "ecosystem \u2014 most published first on X, many already indexed by other `awesome-*` "
        "lists \u2014 classified, credited and recommended. A prompt is optional here; for the "
        "reproducible, contract-checked recipes see [`prompts/`](prompts).",
        "",
        "**Generated by [`scripts/build_catalog.py`](scripts/build_catalog.py)** \u2014 edit the "
        "entries under [`catalog/entries/`](catalog/entries), never this file.",
        "",
        "Browse it as a page: [`site/index.html`](site/index.html) \u00b7 "
        "how tiers are decided: [`catalog/README.md`](catalog/README.md).",
        "",
        "| Tier | Meaning |",
        "| --- | --- |",
        "| \u2b50 featured | Editor-picked: high signal, attributable, clearly useful. |",
        "| \u2726 notable | Real traction or a clearly original contribution. |",
        "| \u00b7 community | Surfaced or submitted, not yet vetted. |",
        "",
        "---",
        "",
    ]

    for category, heading in CATEGORIES.items():
        rows = [e for e in entries if e["category"] == category]
        if not rows:
            continue
        rows.sort(key=lambda e: (TIER_ORDER.index(e["tier"]), e["id"]))
        lines += [f"## {heading}", ""]
        lines += ["| Tier | Entry | Kind | Prompt | Source | Stars |", "| --- | --- | --- | --- | --- | --- |"]
        for e in rows:
            stars = e["stars"] if e["stars"] is not None else "\u2014"
            prompt = "yes" if e["has_prompt"] else "no"
            link = f"[{e['title']}]({e['path']})"
            source = f"[{e['source_platform']}]({e['source_url']})"
            lines.append(
                f"| {TIER_BADGE[e['tier']]} | {link} | {KIND_LABEL[e['kind']]} "
                f"| {prompt} | {source} | {stars} |"
            )
        lines.append("")

    lines += ["---", "", f"_{total} entries. Source snapshots, star counts and links as recorded "
              f"on {max(e['added'] for e in entries)}._", ""]
    return "\n".join(lines)


def render_site(entries: list[dict]) -> str:
    data = json.dumps(entries, ensure_ascii=False)
    cats = json.dumps([[c, CATEGORIES[c].split("\u2014")[0].strip()] for c in CATEGORIES], ensure_ascii=False)
    return ("""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>GPT-6 Astra Catalog</title>
<meta name="description" content="A classified, credited, recommended index of GPT-6 Astra prompts, demos, tools and guides.">
<style>
:root{--bg:#0b0d12;--card:#141824;--line:#242a3a;--fg:#e8ecf5;--dim:#98a2b8}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.55 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif}
header{padding:40px 24px 8px;max-width:1100px;margin:0 auto}
h1{font-size:28px;margin:0 0 8px}
.sub{color:var(--dim);max-width:70ch}
.controls{position:sticky;top:0;z-index:2;background:linear-gradient(var(--bg) 70%,transparent);padding:14px 24px 10px;max-width:1100px;margin:0 auto}
.row{display:flex;flex-wrap:wrap;gap:8px;margin:6px 0}
button{background:var(--card);color:var(--fg);border:1px solid var(--line);border-radius:999px;padding:6px 13px;cursor:pointer;font-size:13px}
button[aria-pressed="true"]{background:#2a3350;border-color:#4a5d94}
input[type=search]{background:var(--card);color:var(--fg);border:1px solid var(--line);border-radius:10px;padding:9px 12px;width:min(420px,100%);font-size:14px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:14px;max-width:1100px;margin:0 auto;padding:8px 24px 64px}
.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:16px 16px 14px;display:flex;flex-direction:column;gap:8px}
.card h3{margin:0;font-size:16px}
.meta{display:flex;flex-wrap:wrap;gap:6px;font-size:12px}
.pill{border:1px solid var(--line);border-radius:999px;padding:2px 9px;color:var(--dim)}
.pill.f{color:#ffd479;border-color:#5a4a1a}
.pill.n{color:#a7d8ff}
.pill.p{color:#8ce0b0;border-color:#1f4a33}
.what{color:var(--fg)}
.why{color:var(--dim);font-size:13.5px}
.src{font-size:13px;color:var(--dim);margin-top:auto}
a{color:#9db8ff}
.count{color:var(--dim);font-size:13px;padding:4px 0}
</style>
</head>
<body>
<header>
  <h1>GPT-6 Astra Catalog</h1>
  <p class="sub">A classified, credited, recommended index of GPT-6 Astra prompts, demos, tools and guides \u2014 sourced from X and community <code>awesome-*</code> lists. A prompt is optional; every entry carries a real source.</p>
  <p class="sub"><a href="https://github.com/yangzhou-chaofan/awesome-gpt6-astra-game-prompts">Repository</a> \u00b7 <a href="https://github.com/yangzhou-chaofan/awesome-gpt6-astra-game-prompts/blob/main/CATALOG.md">CATALOG.md</a></p>
</header>
<div class="controls">
  <input id="q" type="search" placeholder="Search title, tag, author, what it does\u2026">
  <div class="row" id="cats"></div>
  <div class="row" id="tiers"></div>
  <div class="count" id="count"></div>
</div>
<main class="grid" id="grid"></main>
<script>
const DATA = __DATA__;
const CATS = __CATS__;
const TIERS = [["featured","\u2b50 featured"],["notable","\u2726 notable"],["community","\u00b7 community"]];
const state = {cat:"all", tier:"all", prompt:"all", q:""};
const $ = s => document.querySelector(s);
function chips(host, items, key){
  items.forEach(([v,label]) => {
    const b=document.createElement("button");
    b.textContent=label; b.dataset.v=v;
    b.setAttribute("aria-pressed", state[key]===v);
    b.onclick=()=>{state[key]=v; render();};
    host.appendChild(b);
  });
}
function render(){
  document.querySelectorAll("#cats button").forEach(b=>b.setAttribute("aria-pressed", state.cat===b.dataset.v));
  document.querySelectorAll("#tiers button").forEach(b=>b.setAttribute("aria-pressed", state.tier===b.dataset.v));
  const q=state.q.toLowerCase();
  const rows=DATA.filter(e =>
    (state.cat==="all"||e.category===state.cat) &&
    (state.tier==="all"||e.tier===state.tier) &&
    (state.prompt==="all"||(state.prompt==="yes")===e.has_prompt) &&
    (!q || [e.title,e.author,e.what,e.why,(e.tags||[]).join(" "),(e.signals||[]).join(" ")].join(" ").toLowerCase().includes(q))
  );
  const g=$("#grid"); g.innerHTML="";
  $("#count").textContent = rows.length + " of " + DATA.length + " entries";
  rows.forEach(e=>{
    const c=document.createElement("article"); c.className="card";
    const srcTxt={github:"GitHub",x:"X",web:"Web",hf:"Hugging Face"}[e.source_platform]||e.source_platform;
    const stars = (e.stars!==null&&e.stars!==undefined) ? " \u00b7 \u2605 "+e.stars : "";
    c.innerHTML = `<h3>${esc(e.title)}</h3>
      <div class="meta">
        <span class="pill ${e.tier[0]}">${e.tier}</span>
        <span class="pill">${e.category}</span>
        <span class="pill">${e.kind}</span>
        ${e.has_prompt?'<span class="pill p">prompt</span>':''}
      </div>
      <div class="what">${esc(e.what)}</div>
      <div class="why">${esc(e.why)}</div>
      <div class="src">by <b>${esc(e.author)}</b> \u00b7 <a href="${e.source_url}" target="_blank" rel="noopener">${srcTxt}${stars}</a></div>`;
    g.appendChild(c);
  });
}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
chips($("#cats"), [["all","all categories"],...CATS], "cat");
chips($("#tiers"), [["all","all tiers"],...TIERS], "tier");
const pf=document.createElement("button"); pf.textContent="has prompt";
pf.onclick=()=>{state.prompt = state.prompt==="yes"?"all":"yes"; pf.setAttribute("aria-pressed",state.prompt==="yes"); render();};
$("#tiers").appendChild(pf);
$("#q").addEventListener("input",e=>{state.q=e.target.value; render();});
render();
</script>
</body>
</html>
""").replace("__DATA__", data).replace("__CATS__", cats)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != content:
            print(f"\u2717 {path.relative_to(ROOT)} is stale \u2014 run: python3 scripts/build_catalog.py")
            return False
        return True
    if path.exists() and path.read_text(encoding="utf-8") == content:
        print(f"\u2713 {path.relative_to(ROOT)} already up to date")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"\u2713 {path.relative_to(ROOT)} regenerated")
    return True


def main() -> int:
    check = "--check" in sys.argv
    if not check:
        result = subprocess.run([sys.executable, str(ROOT / "scripts" / "validate_catalog.py")])
        if result.returncode != 0:
            print("\u2717 catalog validation failed \u2014 fix errors before building")
            return 1

    entries = load()
    ok = write_or_check(CATALOG_MD, render_markdown(entries), check)
    ok = write_or_check(SITE, render_site(entries), check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
